// Builds and reads Talon design files.
//
// Shared by the export/import scripts. Uses no Node or DOM APIs.
//
// A design file is one self-contained HTML page:
//   <style id="talon-base">    the app's built-in styles (read-only)
//   <style id="talon-design">  the role's stylesheet - the only part designers change
//   <script id="talon-app">    the whole Talon frontend, running on sample data
//
// The base block comes first so any @layer a designer (or an AI) declares is
// ordered after the base layer, exactly as it is in the real app.

export const DESIGN_FILE_FORMAT = 2;

export const ROLES = Object.freeze(["login", "student", "supervisor", "admin"]);

export const ROLE_LABELS = Object.freeze({
  login: "Login",
  student: "Student",
  supervisor: "Supervisor",
  admin: "Admin",
});

const MARKER_START = "/* ===== YOUR DESIGN STARTS HERE: change anything below this line ===== */";
const MARKER_END = "/* ===== YOUR DESIGN ENDS HERE ===== */";
// Matches the markers even if their wording was edited slightly.
const MARKER_PATTERN = /\/\*[^*]*YOUR DESIGN (?:STARTS|ENDS) HERE[\s\S]*?\*\//g;

/** Line endings and surrounding whitespace never count as a design change. */
export function normalizeCss(css) {
  return String(css ?? "").replace(/\r\n?/g, "\n").trim();
}

export function wrapDesignCss(css) {
  return `\n${MARKER_START}\n\n${normalizeCss(css)}\n\n${MARKER_END}\n`;
}

export function unwrapDesignCss(text) {
  return normalizeCss(String(text ?? "").replace(MARKER_PATTERN, ""));
}

function escapeAttribute(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function unescapeAttribute(value) {
  return value.replace(/&quot;/g, '"').replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");
}

// A literal "</style" or "</script" inside the text would end the element early.
// "<\/" means the same thing in CSS strings and JavaScript, so this is safe. It is
// also idempotent (the escaped form no longer matches).
function protectRawText(text, tagName) {
  return String(text ?? "").replace(new RegExp(`</${tagName}`, "gi"), (match) => `<\\/${match.slice(2)}`);
}

// ---------- Building ----------

export function buildDesignFile({ role, meta, baseCss, designCss, appJs }) {
  if (!ROLES.includes(role)) throw new Error(`Unknown design role: ${role}`);
  const label = ROLE_LABELS[role];

  const metaTags = [
    ["talon-design-format", DESIGN_FILE_FORMAT],
    ["talon-design-role", role],
    ["talon-design-exported-at", meta.exportedAt],
    ["talon-design-source", meta.sourceFingerprint],
    ["talon-design-baseline", meta.baselineHash],
    ["talon-design-base", meta.baseHash],
  ]
    .map(([name, value]) => `<meta name="${name}" content="${escapeAttribute(value)}">`)
    .join("\n");

  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>Talon Design - ${label} View</title>`,
    metaTags,
    "<!--",
    `  TALON DESIGN FILE: ${label.toUpperCase()} VIEW`,
    "",
    "  HOW TO USE THIS FILE",
    "  1. Double-click this file. It opens in your web browser as a working copy",
    `     of the Talon ${label} screen, filled with sample data.`,
    "  2. Give this complete HTML file to an AI coding tool and describe the look",
    "     you want. Ask it to edit the file and return the complete HTML file.",
    "  3. Open the returned file in a browser to review the result.",
    "  4. Return that one HTML file to the project owner.",
    "",
    "  Do not open this file in Word, Pages, or TextEdit: they damage it.",
    "",
    "  NOTE FOR AI ASSISTANTS",
    "  If you were given this whole file and asked to change how it looks:",
    "  - Only the CSS between the YOUR DESIGN STARTS HERE and YOUR DESIGN ENDS HERE",
    "    markers can be changed. Everything else is the compiled app.",
    "  - Return the complete edited HTML file. Preserve every part outside the",
    "    design markers exactly, especially the compiled script at the end.",
    "  - Do not rewrite this as a new web page or shorten it. A rebuilt or partial",
    "    file cannot be imported into Talon.",
    "  - The page's HTML is generated by that script, so it is not visible here.",
    "    The class names available for styling are listed at the top of the CSS.",
    "  - Restyle existing elements only. Do not add elements or change any words.",
    "-->",
    "<!-- The app's built-in styles. Please do not edit them. -->",
    `<style id="talon-base">${protectRawText(baseCss, "style")}</style>`,
    `<style id="talon-design">${protectRawText(wrapDesignCss(designCss), "style")}</style>`,
    "</head>",
    "<body>",
    '<div id="root"></div>',
    "<!-- AI ASSISTANTS: the script below is the compiled Talon app. Do not read, change, shorten, or reproduce it. -->",
    `<script type="module" id="talon-app">${protectRawText(appJs, "script")}</script>`,
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

// ---------- Reading ----------

const RAW_TEXT_ELEMENTS = new Set(["script", "style", "title", "textarea"]);

// Walks the markup the way a browser tokenizer does: comments are skipped, and the
// contents of <style>/<script> are consumed as raw text. Plain regexes are not
// enough here, because the instructions comment at the top of every file mentions
// these tags and a regex would match that text first.
function scanHtml(html) {
  const text = String(html ?? "");
  const lower = text.toLowerCase();
  const tags = [];
  const rawBlocks = [];
  let i = 0;

  while (i < text.length) {
    const lt = text.indexOf("<", i);
    if (lt === -1) break;

    if (text.startsWith("<!--", lt)) {
      const end = text.indexOf("-->", lt + 4);
      i = end === -1 ? text.length : end + 3;
      continue;
    }

    const open = /^<([a-zA-Z][\w-]*)\b([^>]*)>/.exec(text.slice(lt, lt + 4096));
    if (!open) {
      i = lt + 1;
      continue;
    }

    const name = open[1].toLowerCase();
    const attrs = open[2];
    const contentStart = lt + open[0].length;
    tags.push({ name, attrs });

    if (RAW_TEXT_ELEMENTS.has(name)) {
      const close = lower.indexOf(`</${name}`, contentStart);
      const contentEnd = close === -1 ? text.length : close;
      rawBlocks.push({ name, attrs, content: text.slice(contentStart, contentEnd) });
      const closeEnd = close === -1 ? -1 : text.indexOf(">", close);
      i = closeEnd === -1 ? text.length : closeEnd + 1;
      continue;
    }

    i = contentStart;
  }

  return { text, tags, rawBlocks };
}

function attribute(attrs, name) {
  const match = new RegExp(`(?:^|\\s)${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s"'>]+))`, "i").exec(attrs);
  return match ? unescapeAttribute(match[1] ?? match[2] ?? match[3] ?? "") : null;
}

export function readDesignFile(html) {
  const { text, tags, rawBlocks } = scanHtml(html);

  const meta = (name) => {
    const tag = tags.find((t) => t.name === "meta" && attribute(t.attrs, "name") === name);
    return tag ? attribute(tag.attrs, "content") ?? "" : "";
  };

  const styles = rawBlocks
    .filter((block) => block.name === "style")
    .map((block) => ({ id: attribute(block.attrs, "id") ?? "", content: block.content }));
  const design = styles.find((style) => style.id === "talon-design");
  const base = styles.find((style) => style.id === "talon-base");

  // Everything except the base styles, in the order the browser applied it. This is
  // what the returned file displays, including any <style> blocks an AI added.
  const combinedCss = normalizeCss(
    styles
      .filter((style) => style.id !== "talon-base")
      .map((style) => (style.id === "talon-design" ? unwrapDesignCss(style.content) : style.content))
      .join("\n\n")
  );

  const title = rawBlocks.find((block) => block.name === "title")?.content ?? "";
  const bodyIndex = tags.findIndex((t) => t.name === "body");
  const addedMarkup =
    bodyIndex !== -1 &&
    tags
      .slice(bodyIndex + 1)
      .some((t) => !(t.name === "script" || (t.name === "div" && attribute(t.attrs, "id") === "root")));

  return {
    format: meta("talon-design-format"),
    role: meta("talon-design-role"),
    roleFromTitle: /\b(login|student|supervisor|admin)\s+view\b/i.exec(title)?.[1]?.toLowerCase() ?? "",
    exportedAt: meta("talon-design-exported-at"),
    sourceFingerprint: meta("talon-design-source"),
    baselineHash: meta("talon-design-baseline"),
    baseHash: meta("talon-design-base"),
    designCss: design ? unwrapDesignCss(design.content) : null,
    combinedCss,
    extraStyleCount: styles.filter((style) => style.id !== "talon-design" && style.id !== "talon-base").length,
    baseCss: base ? base.content : null,
    hasApp: rawBlocks.some((block) => block.name === "script" && attribute(block.attrs, "id") === "talon-app"),
    addedMarkup,
    looksLikeWord:
      /urn:schemas-microsoft-com:office/i.test(text) ||
      tags.some((t) => t.name === "meta" && /microsoft word/i.test(attribute(t.attrs, "content") ?? "")),
  };
}
