// Generates seed/seed.sql, including real PBKDF2 password hashes for the demo
// accounts. Run with:  npm run db:seed:generate --workspace=server
//
// Hashes are produced here with the same Web Crypto algorithm and the same
// self-describing format the Worker verifies against, so they interoperate.
//
// Timestamps are unix SECONDS because the Drizzle schema uses
// integer({ mode: "timestamp" }), which stores seconds.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { INITIAL_DEPARTMENT_CODES } from "./departmentCodes.mjs";

const ITERATIONS = Number(process.env.PBKDF2_ITERATIONS ?? 600_000);
const encoder = new TextEncoder();

function toBase64(bytes) {
  return Buffer.from(bytes).toString("base64");
}

async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const key = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, [
    "deriveBits",
  ]);
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations: ITERATIONS, hash: "SHA-256" },
    key,
    256
  );
  return `pbkdf2$${ITERATIONS}$${toBase64(salt)}$${toBase64(new Uint8Array(bits))}`;
}

/** Escapes a value for a single-quoted SQL string literal. */
const q = (value) => `'${String(value).replace(/'/g, "''")}'`;

const now = Math.floor(Date.now() / 1000);

const demoUsers = [
  {
    email: "admin@tntech.edu",
    password: "ChangeMe!Admin1",
    firstName: "Ada",
    lastName: "Admin",
    role: "ADMIN",
    payType: "MONTHLY",
    annualSalaryCents: 6_500_000,
    hourlyRateCents: null,
  },
  {
    email: "supervisor@tntech.edu",
    password: "ChangeMe!Super1",
    firstName: "Sam",
    lastName: "Supervisor",
    role: "SUPERVISOR",
    payType: "MONTHLY",
    annualSalaryCents: 5_800_000,
    hourlyRateCents: null,
  },
  {
    email: "student@tntech.edu",
    password: "ChangeMe!Student1",
    firstName: "Stu",
    lastName: "Student",
    role: "STUDENT",
    payType: "BIWEEKLY",
    annualSalaryCents: null,
    hourlyRateCents: 1150,
  },
];

const lines = [
  "-- Generated by seed/generate-seed.mjs - do not edit by hand.",
  "-- Demo passwords are in the README; rotate them before using real data.",
  "",
  "DELETE FROM audit_logs;",
  "DELETE FROM report_runs;",
  "DELETE FROM pay_stubs;",
  "DELETE FROM pay_periods;",
  "DELETE FROM time_entries;",
  "DELETE FROM refresh_tokens;",
  "DELETE FROM users;",
  "DELETE FROM departments;",
  "DELETE FROM colleges;",
  "",
  "-- Colleges",
  `INSERT INTO colleges (id, name, code, created_at, updated_at) VALUES (1, 'College of Engineering', 'COE', ${now}, ${now});`,
  `INSERT INTO colleges (id, name, code, created_at, updated_at) VALUES (2, 'College of Arts & Sciences', 'CAS', ${now}, ${now});`,
  "",
  "-- Departments: full registrar code list. CSC and MATH get real names and a",
  "-- college so the demo shows both assigned and unassigned states.",
];

INITIAL_DEPARTMENT_CODES.forEach((code, index) => {
  const id = index + 1;
  let name = code;
  let collegeId = "NULL";
  if (code === "CSC") {
    name = "Computer Science";
    collegeId = "1";
  } else if (code === "MATH") {
    name = "Mathematics";
    collegeId = "2";
  }
  lines.push(
    `INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (${id}, ${q(name)}, ${q(code)}, ${collegeId}, 1, ${now}, ${now});`
  );
});

const cscId = INITIAL_DEPARTMENT_CODES.indexOf("CSC") + 1;

lines.push("", "-- Demo users");

for (const [index, user] of demoUsers.entries()) {
  const id = index + 1;
  const hash = await hashPassword(user.password);
  // The student reports to the supervisor (id 2) so the approval queue has data.
  const supervisorId = user.role === "STUDENT" ? "2" : "NULL";
  lines.push(
    `INSERT INTO users (id, email, password_hash, first_name, last_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, supervisor_id, is_active, must_reset_pw, created_at, updated_at) VALUES (${id}, ${q(user.email)}, ${q(hash)}, ${q(user.firstName)}, ${q(user.lastName)}, ${q(user.role)}, ${q(user.payType)}, ${user.hourlyRateCents ?? "NULL"}, ${user.annualSalaryCents ?? "NULL"}, ${cscId}, ${supervisorId}, 1, 0, ${now}, ${now});`
  );
}

// A little history so the dashboards are not empty on first login.
const DAY = 86_400;
const HOUR = 3_600;
lines.push("", "-- Sample time entries for the student (user 3)");
lines.push(
  `INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, created_at, updated_at) VALUES (1, 3, ${now - 6 * DAY + 9 * HOUR}, ${now - 6 * DAY + 13 * HOUR}, 'WEB', 'APPROVED', ${now}, ${now});`
);
lines.push(
  `INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, created_at, updated_at) VALUES (2, 3, ${now - 4 * DAY + 9 * HOUR}, ${now - 4 * DAY + 17 * HOUR}, 'WEB', 'APPROVED', ${now}, ${now});`
);
lines.push(
  `INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, created_at, updated_at) VALUES (3, 3, ${now - 1 * DAY + 9 * HOUR}, ${now - 1 * DAY + 14 * HOUR}, 'WEB', 'PENDING', ${now}, ${now});`
);

lines.push("", "-- Pay periods");
// The biweekly period deliberately spans the sample time entries above so that
// generating stubs produces real hours and pay rather than an empty $0 stub.
lines.push(
  `INSERT INTO pay_periods (id, type, start_date, end_date, pay_date, status, created_at, updated_at) VALUES (1, 'BIWEEKLY', ${now - 14 * DAY}, ${now}, ${now + 3 * DAY}, 'OPEN', ${now}, ${now});`
);
lines.push(
  `INSERT INTO pay_periods (id, type, start_date, end_date, pay_date, status, created_at, updated_at) VALUES (2, 'MONTHLY', ${now - 30 * DAY}, ${now}, ${now + 2 * DAY}, 'OPEN', ${now}, ${now});`
);

const outPath = join(dirname(fileURLToPath(import.meta.url)), "seed.sql");
writeFileSync(outPath, lines.join("\n") + "\n", "utf8");
console.log(`Wrote ${outPath}`);
console.log(`Departments: ${INITIAL_DEPARTMENT_CODES.length}, users: ${demoUsers.length}`);
console.log(`PBKDF2 iterations: ${ITERATIONS}`);
