-- Generated by seed/generate-seed.mjs - do not edit by hand.
-- Demo passwords are in the README; rotate them before using real data.

DELETE FROM audit_logs;
DELETE FROM report_runs;
DELETE FROM pay_stubs;
DELETE FROM pay_periods;
DELETE FROM time_entries;
DELETE FROM refresh_tokens;
DELETE FROM users;
DELETE FROM departments;
DELETE FROM colleges;

-- Colleges
INSERT INTO colleges (id, name, code, created_at, updated_at) VALUES (1, 'College of Engineering', 'COE', 1789406163, 1789406163);
INSERT INTO colleges (id, name, code, created_at, updated_at) VALUES (2, 'College of Arts & Sciences', 'CAS', 1789406163, 1789406163);

-- Departments: full registrar code list. CSC and MATH get real names and a
-- college so the demo shows both assigned and unassigned states.
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (1, 'ACCT', 'ACCT', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (2, 'AGBE', 'AGBE', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (3, 'AGCM', 'AGCM', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (4, 'AGED', 'AGED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (5, 'AGET', 'AGET', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (6, 'AGHT', 'AGHT', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (7, 'AGR', 'AGR', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (8, 'AGRN', 'AGRN', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (9, 'AI', 'AI', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (10, 'ANPS', 'ANPS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (11, 'ANS', 'ANS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (12, 'ARED', 'ARED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (13, 'ART', 'ART', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (14, 'ASTR', 'ASTR', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (15, 'BIOL', 'BIOL', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (16, 'BMGT', 'BMGT', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (17, 'CEE', 'CEE', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (18, 'CESL', 'CESL', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (19, 'CHE', 'CHE', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (20, 'CHEM', 'CHEM', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (21, 'CJ', 'CJ', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (22, 'COMM', 'COMM', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (23, 'COUN', 'COUN', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (24, 'Computer Science', 'CSC', 1, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (25, 'CSED', 'CSED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (26, 'CUED', 'CUED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (27, 'DLED', 'DLED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (28, 'DS', 'DS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (29, 'ECE', 'ECE', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (30, 'ECED', 'ECED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (31, 'ECON', 'ECON', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (32, 'ECSP', 'ECSP', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (33, 'EDU', 'EDU', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (34, 'EDUB', 'EDUB', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (35, 'EDUH', 'EDUH', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (36, 'EDUL', 'EDUL', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (37, 'EDUP', 'EDUP', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (38, 'EDUS', 'EDUS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (39, 'ELED', 'ELED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (40, 'EMGT', 'EMGT', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (41, 'ENGL', 'ENGL', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (42, 'ENGR', 'ENGR', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (43, 'ESL', 'ESL', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (44, 'ESLP', 'ESLP', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (45, 'ESOL', 'ESOL', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (46, 'ESS', 'ESS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (47, 'EVS', 'EVS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (48, 'EVSA', 'EVSA', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (49, 'EVSB', 'EVSB', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (50, 'EVSC', 'EVSC', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (51, 'EVSI', 'EVSI', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (52, 'EXPW', 'EXPW', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (53, 'FIN', 'FIN', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (54, 'FOED', 'FOED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (55, 'FREN', 'FREN', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (56, 'GEOG', 'GEOG', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (57, 'GEOL', 'GEOL', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (58, 'GERM', 'GERM', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (59, 'HEC', 'HEC', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (60, 'HIST', 'HIST', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (61, 'HON', 'HON', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (62, 'HRED', 'HRED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (63, 'IC', 'IC', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (64, 'INSL', 'INSL', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (65, 'ISE', 'ISE', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (66, 'JOUR', 'JOUR', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (67, 'LAW', 'LAW', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (68, 'LING', 'LING', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (69, 'LIST', 'LIST', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (70, 'LSCI', 'LSCI', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (71, 'Mathematics', 'MATH', 2, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (72, 'MBA', 'MBA', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (73, 'ME', 'ME', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (74, 'MET', 'MET', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (75, 'MKT', 'MKT', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (76, 'MS', 'MS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (77, 'MUED', 'MUED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (78, 'MUS', 'MUS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (79, 'MUSA', 'MUSA', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (80, 'NRSE', 'NRSE', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (81, 'Nuclear Engineering', 'Nuclear Engineering', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (82, 'NURS', 'NURS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (83, 'PC', 'PC', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (84, 'PHED', 'PHED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (85, 'PHIL', 'PHIL', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (86, 'PHYS', 'PHYS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (87, 'POLS', 'POLS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (88, 'PRST', 'PRST', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (89, 'PSY', 'PSY', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (90, 'READ', 'READ', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (91, 'RELS', 'RELS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (92, 'SA', 'SA', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (93, 'SEED', 'SEED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (94, 'SOC', 'SOC', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (95, 'SPAN', 'SPAN', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (96, 'SPED', 'SPED', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (97, 'SVCL', 'SVCL', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (98, 'SW', 'SW', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (99, 'THEA', 'THEA', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (100, 'UBUS', 'UBUS', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (101, 'UNIV', 'UNIV', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (102, 'UNPP', 'UNPP', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (103, 'VE', 'VE', NULL, 1, 1789406163, 1789406163);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (104, 'WFS', 'WFS', NULL, 1, 1789406163, 1789406163);

-- Demo users
INSERT INTO users (id, email, password_hash, first_name, last_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, supervisor_id, is_active, must_reset_pw, created_at, updated_at) VALUES (1, 'admin@tntech.edu', 'scrypt$32768$8$3$XNSS6nRcwZoyuz9F/+T33Q==$0lhhqHYtW/QeUOoQN32AzOWrUaTwEqmmhHLJIpzsZ9k=', 'Ada', 'Admin', 'ADMIN', 'MONTHLY', NULL, 6500000, 24, NULL, 1, 0, 1789406163, 1789406163);
INSERT INTO users (id, email, password_hash, first_name, last_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, supervisor_id, is_active, must_reset_pw, created_at, updated_at) VALUES (2, 'supervisor@tntech.edu', 'scrypt$32768$8$3$ep+hQtbcRM6YBXteKgGC7A==$VHABS4mM86kC4xS/m+GTKkm6IaaEHwaTk1e+u7N8SaE=', 'Sam', 'Supervisor', 'SUPERVISOR', 'MONTHLY', NULL, 5800000, 24, NULL, 1, 0, 1789406163, 1789406163);
INSERT INTO users (id, email, password_hash, first_name, last_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, supervisor_id, is_active, must_reset_pw, created_at, updated_at) VALUES (3, 'student@tntech.edu', 'scrypt$32768$8$3$PCFVkULteusDTm75Y6sGQA==$ihHMOjehbtFctRVMITTUo3Prl/CxAYB4VSX8xlaUEjQ=', 'Stu', 'Student', 'STUDENT', 'BIWEEKLY', 1150, NULL, 24, 2, 1, 0, 1789406163, 1789406163);

-- Sample time entries for the student (user 3)
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, created_at, updated_at) VALUES (1, 3, 1788920163, 1788934563, 'WEB', 'APPROVED', 1789406163, 1789406163);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, created_at, updated_at) VALUES (2, 3, 1789092963, 1789121763, 'WEB', 'APPROVED', 1789406163, 1789406163);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, created_at, updated_at) VALUES (3, 3, 1789352163, 1789370163, 'WEB', 'PENDING', 1789406163, 1789406163);

-- Pay periods
INSERT INTO pay_periods (id, type, start_date, end_date, pay_date, status, created_at, updated_at) VALUES (1, 'BIWEEKLY', 1788196563, 1789406163, 1789665363, 'OPEN', 1789406163, 1789406163);
INSERT INTO pay_periods (id, type, start_date, end_date, pay_date, status, created_at, updated_at) VALUES (2, 'MONTHLY', 1786814163, 1789406163, 1789578963, 'OPEN', 1789406163, 1789406163);
