-- Generated by seed/generate-seed.mjs - do not edit by hand.
-- Demo passwords are in the README; rotate them before using real data.

DELETE FROM reminder_runs;
DELETE FROM notifications;
DELETE FROM notification_preferences;
DELETE FROM password_reset_tokens;
DELETE FROM audit_logs;
DELETE FROM report_runs;
DELETE FROM pay_stubs;
DELETE FROM pay_periods;
DELETE FROM time_entry_change_requests;
DELETE FROM time_entries;
DELETE FROM refresh_tokens;
DELETE FROM user_profile_photos;
DELETE FROM student_supervisors;
DELETE FROM users;
DELETE FROM charge_accounts;
DELETE FROM departments;
DELETE FROM colleges;

-- Colleges
INSERT INTO colleges (id, name, code, created_at, updated_at) VALUES (1, 'College of Engineering', 'COE', 1791557269, 1791557269);
INSERT INTO colleges (id, name, code, created_at, updated_at) VALUES (2, 'College of Arts & Sciences', 'CAS', 1791557269, 1791557269);

-- Departments: full registrar code list. CSC and MATH get real names and a
-- college so the demo shows both assigned and unassigned states.
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (1, 'ACCT', 'ACCT', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (2, 'AGBE', 'AGBE', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (3, 'AGCM', 'AGCM', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (4, 'AGED', 'AGED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (5, 'AGET', 'AGET', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (6, 'AGHT', 'AGHT', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (7, 'AGR', 'AGR', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (8, 'AGRN', 'AGRN', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (9, 'AI', 'AI', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (10, 'ANPS', 'ANPS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (11, 'ANS', 'ANS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (12, 'ARED', 'ARED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (13, 'ART', 'ART', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (14, 'ASTR', 'ASTR', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (15, 'BIOL', 'BIOL', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (16, 'BMGT', 'BMGT', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (17, 'CEE', 'CEE', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (18, 'CESL', 'CESL', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (19, 'CHE', 'CHE', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (20, 'CHEM', 'CHEM', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (21, 'CJ', 'CJ', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (22, 'COMM', 'COMM', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (23, 'COUN', 'COUN', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (24, 'Computer Science', 'CSC', 1, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (25, 'CSED', 'CSED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (26, 'CUED', 'CUED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (27, 'DLED', 'DLED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (28, 'DS', 'DS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (29, 'ECE', 'ECE', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (30, 'ECED', 'ECED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (31, 'ECON', 'ECON', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (32, 'ECSP', 'ECSP', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (33, 'EDU', 'EDU', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (34, 'EDUB', 'EDUB', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (35, 'EDUH', 'EDUH', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (36, 'EDUL', 'EDUL', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (37, 'EDUP', 'EDUP', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (38, 'EDUS', 'EDUS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (39, 'ELED', 'ELED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (40, 'EMGT', 'EMGT', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (41, 'ENGL', 'ENGL', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (42, 'ENGR', 'ENGR', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (43, 'ESL', 'ESL', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (44, 'ESLP', 'ESLP', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (45, 'ESOL', 'ESOL', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (46, 'ESS', 'ESS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (47, 'EVS', 'EVS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (48, 'EVSA', 'EVSA', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (49, 'EVSB', 'EVSB', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (50, 'EVSC', 'EVSC', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (51, 'EVSI', 'EVSI', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (52, 'EXPW', 'EXPW', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (53, 'FIN', 'FIN', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (54, 'FOED', 'FOED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (55, 'FREN', 'FREN', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (56, 'GEOG', 'GEOG', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (57, 'GEOL', 'GEOL', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (58, 'GERM', 'GERM', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (59, 'HEC', 'HEC', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (60, 'HIST', 'HIST', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (61, 'HON', 'HON', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (62, 'HRED', 'HRED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (63, 'IC', 'IC', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (64, 'INSL', 'INSL', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (65, 'ISE', 'ISE', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (66, 'JOUR', 'JOUR', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (67, 'LAW', 'LAW', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (68, 'LING', 'LING', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (69, 'LIST', 'LIST', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (70, 'LSCI', 'LSCI', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (71, 'Mathematics', 'MATH', 2, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (72, 'MBA', 'MBA', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (73, 'ME', 'ME', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (74, 'MET', 'MET', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (75, 'MKT', 'MKT', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (76, 'MS', 'MS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (77, 'MUED', 'MUED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (78, 'MUS', 'MUS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (79, 'MUSA', 'MUSA', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (80, 'NRSE', 'NRSE', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (81, 'Nuclear Engineering', 'Nuclear Engineering', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (82, 'NURS', 'NURS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (83, 'PC', 'PC', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (84, 'PHED', 'PHED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (85, 'PHIL', 'PHIL', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (86, 'PHYS', 'PHYS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (87, 'POLS', 'POLS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (88, 'PRST', 'PRST', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (89, 'PSY', 'PSY', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (90, 'READ', 'READ', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (91, 'RELS', 'RELS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (92, 'SA', 'SA', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (93, 'SEED', 'SEED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (94, 'SOC', 'SOC', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (95, 'SPAN', 'SPAN', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (96, 'SPED', 'SPED', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (97, 'SVCL', 'SVCL', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (98, 'SW', 'SW', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (99, 'THEA', 'THEA', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (100, 'UBUS', 'UBUS', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (101, 'UNIV', 'UNIV', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (102, 'UNPP', 'UNPP', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (103, 'VE', 'VE', NULL, 1, 1791557269, 1791557269);
INSERT INTO departments (id, name, code, college_id, is_active, created_at, updated_at) VALUES (104, 'WFS', 'WFS', NULL, 1, 1791557269, 1791557269);

-- Charge accounts (Banner index codes)
INSERT INTO charge_accounts (id, code, name, department_id, is_active, created_at, updated_at) VALUES (1, '110245', 'Computer Science Student Workers', 24, 1, 1791557269, 1791557269);
INSERT INTO charge_accounts (id, code, name, department_id, is_active, created_at, updated_at) VALUES (2, '120310', 'Mathematics Tutoring Center', 71, 1, 1791557269, 1791557269);
INSERT INTO charge_accounts (id, code, name, department_id, is_active, created_at, updated_at) VALUES (3, 'G21047', 'NSF REU Research Grant', 71, 1, 1791557269, 1791557269);

-- Demo users (all share the demo password)
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (1, 'admin@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'Renee', 'Admin', NULL, 'ADMIN', 'MONTHLY', NULL, 6500000, 24, NULL, 1, 0, 1791557269, 1791557269);
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (2, 'supervisor@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'Sabrina', 'Supervisor', NULL, 'SUPERVISOR', 'MONTHLY', NULL, 5800000, 24, NULL, 1, 0, 1791557269, 1791557269);
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (3, 'student@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'Chris', 'Student', NULL, 'STUDENT', 'BIWEEKLY', 1150, NULL, 24, 1, 1, 0, 1791557269, 1791557269);
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (4, 'supervisor2@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'Marcus', 'Reyes', NULL, 'SUPERVISOR', 'MONTHLY', NULL, 6100000, 71, NULL, 1, 0, 1791557269, 1791557269);
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (5, 'sophia.wells@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'Sophia', 'Wells', 'Sophie', 'STUDENT', 'BIWEEKLY', 1150, NULL, 24, 3, 1, 0, 1791557269, 1791557269);
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (6, 'robert.hale@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'Robert', 'Hale', NULL, 'STUDENT', 'BIWEEKLY', 1200, NULL, 71, 2, 1, 0, 1791557269, 1791557269);
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (7, 'christopher.lane@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'Christopher', 'Lane', NULL, 'STUDENT', 'BIWEEKLY', 1200, NULL, 71, 2, 1, 0, 1791557269, 1791557269);
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (8, 'elizabeth.park@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'Elizabeth', 'Park', 'Liz', 'STUDENT', 'BIWEEKLY', 1150, NULL, 24, 1, 1, 0, 1791557269, 1791557269);
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (9, 'william.turner@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'William', 'Turner', NULL, 'STUDENT', 'MONTHLY', 1325, NULL, 71, 3, 1, 0, 1791557269, 1791557269);
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (10, 'katherine.diaz@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'Katherine', 'Diaz', NULL, 'STUDENT', 'BIWEEKLY', 1100, NULL, 24, 1, 1, 0, 1791557269, 1791557269);
INSERT INTO users (id, email, password_hash, first_name, last_name, preferred_name, role, pay_type, hourly_rate_cents, annual_salary_cents, department_id, charge_account_id, is_active, must_reset_pw, created_at, updated_at) VALUES (11, 'richard.moss@tntech.edu', 'scrypt$32768$8$3$CENaDKRaJiLZx1EomdpUFA==$0SWFuxseaJp+kElZuYr9gVq28YK6lTCyed538qpxk+w=', 'Richard', 'Moss', NULL, 'STUDENT', 'BIWEEKLY', 1100, NULL, 71, 2, 1, 0, 1791557269, 1791557269);

-- Supervisor assignments (Liz has two supervisors; either can approve)
INSERT INTO student_supervisors (student_id, supervisor_id, created_at) VALUES (3, 2, 1791557269);
INSERT INTO student_supervisors (student_id, supervisor_id, created_at) VALUES (5, 2, 1791557269);
INSERT INTO student_supervisors (student_id, supervisor_id, created_at) VALUES (6, 4, 1791557269);
INSERT INTO student_supervisors (student_id, supervisor_id, created_at) VALUES (7, 4, 1791557269);
INSERT INTO student_supervisors (student_id, supervisor_id, created_at) VALUES (8, 2, 1791557269);
INSERT INTO student_supervisors (student_id, supervisor_id, created_at) VALUES (8, 4, 1791557269);
INSERT INTO student_supervisors (student_id, supervisor_id, created_at) VALUES (9, 4, 1791557269);
INSERT INTO student_supervisors (student_id, supervisor_id, created_at) VALUES (10, 2, 1791557269);
INSERT INTO student_supervisors (student_id, supervisor_id, created_at) VALUES (11, 4, 1791557269);

-- Time entries
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (1, 3, 1789394400, 1789412400, 'WEB', 'APPROVED', 1, 2, NULL, 1789394400, 1789426800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (2, 3, 1789567200, 1789585200, 'WEB', 'APPROVED', 1, 2, NULL, 1789567200, 1789599600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (3, 3, 1790085600, 1790103600, 'WEB', 'APPROVED', 1, 2, NULL, 1790085600, 1790118000);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (4, 3, 1790258400, 1790276400, 'WEB', 'APPROVED', 1, 2, NULL, 1790258400, 1790290800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (5, 5, 1789390800, 1789423200, 'WEB', 'APPROVED', 3, 2, NULL, 1789390800, 1789437600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (6, 5, 1789477200, 1789509600, 'WEB', 'APPROVED', 3, 2, NULL, 1789477200, 1789524000);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (7, 5, 1789563600, 1789596000, 'WEB', 'APPROVED', 3, 2, NULL, 1789563600, 1789610400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (8, 5, 1789650000, 1789682400, 'WEB', 'APPROVED', 3, 2, NULL, 1789650000, 1789696800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (9, 5, 1789736400, 1789768800, 'WEB', 'APPROVED', 3, 2, NULL, 1789736400, 1789783200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (10, 5, 1790085600, 1790100000, 'WEB', 'APPROVED', 3, 2, NULL, 1790085600, 1790114400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (11, 6, 1789408800, 1789423200, 'WEB', 'APPROVED', 2, 4, NULL, 1789408800, 1789437600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (12, 6, 1789668000, 1789682400, 'WEB', 'APPROVED', 2, 4, NULL, 1789668000, 1789696800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (13, 6, 1790013600, 1790028000, 'WEB', 'APPROVED', 2, 4, NULL, 1790013600, 1790042400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (14, 6, 1790186400, 1790200800, 'WEB', 'APPROVED', 2, 4, NULL, 1790186400, 1790215200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (15, 7, 1789484400, 1789506000, 'WEB', 'APPROVED', 2, 4, NULL, 1789484400, 1789520400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (16, 7, 1789743600, 1789765200, 'WEB', 'APPROVED', 2, 4, NULL, 1789743600, 1789779600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (17, 7, 1790089200, 1790110800, 'WEB', 'APPROVED', 2, 4, NULL, 1790089200, 1790125200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (18, 8, 1789480800, 1789502400, 'WEB', 'APPROVED', 1, 2, NULL, 1789480800, 1789516800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (19, 8, 1789653600, 1789675200, 'WEB', 'APPROVED', 1, 2, NULL, 1789653600, 1789689600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (20, 8, 1790190000, 1790204400, 'WEB', 'APPROVED', 2, 2, NULL, 1790190000, 1790218800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (21, 10, 1789570800, 1789588800, 'WEB', 'APPROVED', 1, 2, NULL, 1789570800, 1789603200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (22, 10, 1790175600, 1790193600, 'WEB', 'APPROVED', 1, 2, NULL, 1790175600, 1790208000);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (23, 11, 1789498800, 1789513200, 'WEB', 'APPROVED', 2, 4, NULL, 1789498800, 1789527600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (24, 11, 1790103600, 1790118000, 'WEB', 'APPROVED', 2, 4, NULL, 1790103600, 1790132400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (25, 9, 1788361200, 1788382800, 'WEB', 'APPROVED', 3, 4, NULL, 1788361200, 1788397200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (26, 9, 1788534000, 1788555600, 'WEB', 'APPROVED', 3, 4, NULL, 1788534000, 1788570000);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (27, 9, 1788966000, 1788987600, 'WEB', 'APPROVED', 3, 4, NULL, 1788966000, 1789002000);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (28, 9, 1789138800, 1789160400, 'WEB', 'APPROVED', 3, 4, NULL, 1789138800, 1789174800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (29, 9, 1789570800, 1789592400, 'WEB', 'APPROVED', 3, 4, NULL, 1789570800, 1789606800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (30, 9, 1789743600, 1789765200, 'WEB', 'APPROVED', 3, 4, NULL, 1789743600, 1789779600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (31, 9, 1790175600, 1790197200, 'WEB', 'APPROVED', 3, 4, NULL, 1790175600, 1790211600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (32, 9, 1790348400, 1790370000, 'WEB', 'APPROVED', 3, 4, NULL, 1790348400, 1790384400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (33, 3, 1790604000, 1790622000, 'WEB', 'APPROVED', 1, 2, NULL, 1790604000, 1790636400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (34, 6, 1790618400, 1790632800, 'WEB', 'APPROVED', 2, 4, NULL, 1790618400, 1790647200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (35, 5, 1790690400, 1790712000, 'WEB', 'APPROVED', 3, 2, NULL, 1790690400, 1790726400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (36, 9, 1790694000, 1790715600, 'WEB', 'APPROVED', 3, 4, NULL, 1790694000, 1790730000);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (37, 3, 1790776800, 1790794800, 'WEB', 'APPROVED', 1, 2, NULL, 1790776800, 1790809200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (38, 8, 1790776800, 1790794800, 'WEB', 'APPROVED', 1, 2, NULL, 1790776800, 1790809200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (39, 5, 1790863200, 1790884800, 'WEB', 'APPROVED', 3, 2, NULL, 1790863200, 1790899200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (40, 6, 1790877600, 1790892000, 'WEB', 'APPROVED', 2, 4, NULL, 1790877600, 1790906400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (41, 3, 1791208800, 1791226800, 'WEB', 'APPROVED', 1, 2, NULL, 1791208800, 1791241200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (42, 6, 1791223200, 1791237600, 'WEB', 'APPROVED', 2, 4, NULL, 1791223200, 1791252000);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (43, 5, 1791295200, 1791316800, 'WEB', 'APPROVED', 3, 2, NULL, 1791295200, 1791331200);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (44, 9, 1791298800, 1791320400, 'WEB', 'APPROVED', 3, 4, NULL, 1791298800, 1791334800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (45, 3, 1791381600, 1791399600, 'WEB', 'PENDING', 1, NULL, NULL, 1791381600, 1791399600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (46, 8, 1791381600, 1791399600, 'WEB', 'PENDING', 1, NULL, NULL, 1791381600, 1791399600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (47, 5, 1791468000, 1791489600, 'WEB', 'PENDING', 3, NULL, NULL, 1791468000, 1791489600);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (48, 6, 1791482400, 1791496800, 'WEB', 'PENDING', 2, NULL, NULL, 1791482400, 1791496800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (49, 3, 1791489600, 1791500400, 'WEB', 'PENDING', 1, NULL, NULL, 1791489600, 1791500400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (50, 6, 1791486000, 1791496800, 'WEB', 'PENDING', 2, NULL, NULL, 1791486000, 1791496800);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (51, 8, 1791493200, 1791500400, 'WEB', 'PENDING', 1, NULL, NULL, 1791493200, 1791500400);
INSERT INTO time_entries (id, user_id, clock_in, clock_out, source, status, charge_account_id, edited_by_id, rejection_reason, created_at, updated_at) VALUES (52, 10, 1791298800, 1791331200, 'WEB', 'REJECTED', 1, 2, 'Clock-out was left running past the end of your shift.', 1791298800, 1791345600);

-- Correction requests awaiting a supervisor
INSERT INTO time_entry_change_requests (id, user_id, time_entry_id, requested_clock_in, requested_clock_out, reason, status, created_at, updated_at) VALUES (1, 5, NULL, 1791396000, 1791406800, 'I worked the evening lab shift but the kiosk was down.', 'PENDING', 1791463669, 1791463669);
INSERT INTO time_entry_change_requests (id, user_id, time_entry_id, requested_clock_in, requested_clock_out, reason, status, created_at, updated_at) VALUES (2, 7, NULL, 1791212400, 1791226800, 'Forgot to clock in for my tutoring hours.', 'PENDING', 1791298069, 1791298069);

-- Pay periods
INSERT INTO pay_periods (id, type, start_date, end_date, pay_date, status, created_at, updated_at) VALUES (1, 'BIWEEKLY', 1790553600, 1791763199, 1792108800, 'OPEN', 1791557269, 1791557269);
INSERT INTO pay_periods (id, type, start_date, end_date, pay_date, status, created_at, updated_at) VALUES (2, 'MONTHLY', 1790812800, 1793491199, 1793404800, 'OPEN', 1791557269, 1791557269);
INSERT INTO pay_periods (id, type, start_date, end_date, pay_date, status, created_at, updated_at) VALUES (3, 'BIWEEKLY', 1789344000, 1790553599, 1790899200, 'PROCESSING', 1791557269, 1791557269);
INSERT INTO pay_periods (id, type, start_date, end_date, pay_date, status, created_at, updated_at) VALUES (4, 'MONTHLY', 1788220800, 1790812799, 1790726400, 'PROCESSING', 1791557269, 1791557269);

-- Pay stubs for the generated periods (review pending unless noted)
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (1, 3, 3, 1200, 0, 1150, 23000, 0, 23000, 'DRAFT', 1791470869, 'APPROVED', 2, 1791514069, NULL, NULL, NULL);
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (2, 5, 3, 2640, 300, 1150, 50600, 8625, 59225, 'DRAFT', 1791470869, 'PENDING', NULL, NULL, NULL, NULL, NULL);
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (3, 6, 3, 960, 0, 1200, 19200, 0, 19200, 'DRAFT', 1791470869, 'PENDING', NULL, NULL, NULL, NULL, NULL);
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (4, 7, 3, 1080, 0, 1200, 21600, 0, 21600, 'DRAFT', 1791470869, 'PENDING', NULL, NULL, NULL, NULL, NULL);
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (5, 8, 3, 960, 0, 1150, 18400, 0, 18400, 'DRAFT', 1791470869, 'PENDING', NULL, NULL, NULL, NULL, NULL);
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (6, 10, 3, 600, 0, 1100, 11000, 0, 11000, 'DRAFT', 1791470869, 'PENDING', NULL, NULL, NULL, NULL, NULL);
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (7, 11, 3, 480, 0, 1100, 8800, 0, 8800, 'DRAFT', 1791470869, 'PENDING', NULL, NULL, 'Hours look low for this period. Was a tutoring shift missed?', 1, 1791485269);
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (8, 1, 4, 0, 0, NULL, 541667, 0, 541667, 'DRAFT', 1791470869, 'PENDING', NULL, NULL, NULL, NULL, NULL);
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (9, 2, 4, 0, 0, NULL, 483333, 0, 483333, 'DRAFT', 1791470869, 'PENDING', NULL, NULL, NULL, NULL, NULL);
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (10, 4, 4, 0, 0, NULL, 508333, 0, 508333, 'DRAFT', 1791470869, 'PENDING', NULL, NULL, NULL, NULL, NULL);
INSERT INTO pay_stubs (id, user_id, pay_period_id, regular_minutes, overtime_minutes, hourly_rate_cents, regular_pay_cents, overtime_pay_cents, gross_pay_cents, status, generated_at, review_status, reviewed_by_id, reviewed_at, flag_note, flagged_by_id, flagged_at) VALUES (11, 9, 4, 3240, 0, 1325, 71550, 0, 71550, 'DRAFT', 1791470869, 'PENDING', NULL, NULL, NULL, NULL, NULL);

-- Each supervisor has a payroll report to check (cleared when they open it)
INSERT INTO notifications (recipient_user_id, sender_user_id, type, title, body, action, requires_action, created_at) VALUES (2, 1, 'REPORT_READY', 'Payroll report ready', 'Please review the payroll report for your students.', 'OPEN_REPORT', 1, 1791535669);
INSERT INTO notifications (recipient_user_id, sender_user_id, type, title, body, action, requires_action, created_at) VALUES (4, 1, 'REPORT_READY', 'Payroll report ready', 'Please review the payroll report for your students.', 'OPEN_REPORT', 1, 1791535669);
